import { Controller, Get, Res, Logger } from "@nestjs/common";
import { Response } from "express";
import { Public } from "../../common/decorators/public.decorator";

@Public()
@Controller("webchat")
export class WebChatWidgetController {
  private readonly logger = new Logger(WebChatWidgetController.name);

  @Get("widget.js")
  serveWidget(@Res() res: Response): void {
    res.setHeader("Content-Type", "application/javascript");
    res.setHeader("Cache-Control", "public, max-age=3600");

    const js = [
      "(function() {",
      "  var script = document.currentScript;",
      "  var widgetId = script.getAttribute('data-widget-id') || '';",
      "  var businessId = script.getAttribute('data-business-id') || '';",
      "  var primaryColor = script.getAttribute('data-primary-color') || '#6366f1';",
      "",
      "  var host = script.src.replace(/\\/v1\\/webchat\\/widget\\.js.*/, '');",
      "  var wsUrl = host.replace(/^http/, 'ws') + '/webchat';",
      "",
      "  // Create floating button",
      "  var btn = document.createElement('div');",
      "  btn.id = 'gosumo-chat-btn';",
      "  btn.innerHTML = '<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"white\"><path d=\"M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H6l-2 2V4h16v12z\"/></svg>';",
      "  btn.style.cssText = 'position:fixed;bottom:20px;right:20px;width:56px;height:56px;border-radius:50%;background:' + primaryColor + ';display:flex;align-items:center;justify-content:center;cursor:pointer;box-shadow:0 4px 12px rgba(0,0,0,0.15);z-index:99999;transition:transform 0.2s;';",
      "  document.body.appendChild(btn);",
      "",
      "  // Create chat panel",
      "  var panel = document.createElement('div');",
      "  panel.id = 'gosumo-chat-panel';",
      "  panel.style.cssText = 'position:fixed;bottom:90px;right:20px;width:380px;height:520px;border-radius:12px;background:white;box-shadow:0 8px 30px rgba(0,0,0,0.12);z-index:99999;display:none;flex-direction:column;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,sans-serif;';",
      "",
      "  var header = document.createElement('div');",
      "  header.style.cssText = 'padding:16px;background:' + primaryColor + ';color:white;font-weight:600;font-size:16px;display:flex;justify-content:space-between;align-items:center;';",
      "  header.innerHTML = '<span>Chat with us</span><span style=\"cursor:pointer;font-size:20px\" id=\"gosumo-close\">&times;</span>';",
      "  panel.appendChild(header);",
      "",
      "  var messages = document.createElement('div');",
      "  messages.id = 'gosumo-messages';",
      "  messages.style.cssText = 'flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:8px;';",
      "  panel.appendChild(messages);",
      "",
      "  var inputArea = document.createElement('div');",
      "  inputArea.style.cssText = 'padding:12px;border-top:1px solid #e5e7eb;display:flex;gap:8px;';",
      "  var input = document.createElement('input');",
      "  input.type = 'text';",
      "  input.placeholder = 'Type a message...';",
      "  input.style.cssText = 'flex:1;border:1px solid #d1d5db;border-radius:8px;padding:8px 12px;outline:none;font-size:14px;';",
      "  var sendBtn = document.createElement('button');",
      "  sendBtn.textContent = 'Send';",
      "  sendBtn.style.cssText = 'background:' + primaryColor + ';color:white;border:none;border-radius:8px;padding:8px 16px;cursor:pointer;font-size:14px;';",
      "  inputArea.appendChild(input);",
      "  inputArea.appendChild(sendBtn);",
      "  panel.appendChild(inputArea);",
      "  document.body.appendChild(panel);",
      "",
      "  var isOpen = false;",
      "  var socket = null;",
      "  var sessionId = null;",
      "",
      "  function addMessage(text, isUser) {",
      "    var msg = document.createElement('div');",
      "    msg.style.cssText = 'max-width:80%;padding:8px 12px;border-radius:12px;font-size:14px;line-height:1.4;word-wrap:break-word;' +",
      "      (isUser ? 'background:' + primaryColor + ';color:white;align-self:flex-end;border-bottom-right-radius:4px;' : 'background:#f3f4f6;color:#1f2937;align-self:flex-start;border-bottom-left-radius:4px;');",
      "    msg.textContent = text;",
      "    messages.appendChild(msg);",
      "    messages.scrollTop = messages.scrollHeight;",
      "  }",
      "",
      "  function connect() {",
      "    if (typeof io === 'undefined') {",
      "      var s = document.createElement('script');",
      "      s.src = host + '/socket.io/socket.io.js';",
      "      s.onload = function() { initSocket(); };",
      "      document.head.appendChild(s);",
      "    } else {",
      "      initSocket();",
      "    }",
      "  }",
      "",
      "  function initSocket() {",
      "    socket = io(wsUrl, { query: { widgetId: widgetId }, transports: ['websocket', 'polling'] });",
      "    socket.on('connect', function() {",
      "      socket.emit('chat:init', { widgetId: widgetId, sessionId: sessionId }, function(resp) {",
      "        sessionId = resp.sessionId;",
      "        if (resp.greeting) addMessage(resp.greeting, false);",
      "      });",
      "    });",
      "    socket.on('chat:response', function(data) {",
      "      addMessage(data.text, false);",
      "    });",
      "  }",
      "",
      "  function sendMessage() {",
      "    var text = input.value.trim();",
      "    if (!text || !socket || !sessionId) return;",
      "    addMessage(text, true);",
      "    socket.emit('chat:message', { sessionId: sessionId, text: text });",
      "    input.value = '';",
      "  }",
      "",
      "  btn.addEventListener('click', function() {",
      "    isOpen = !isOpen;",
      "    panel.style.display = isOpen ? 'flex' : 'none';",
      "    if (isOpen && !socket) connect();",
      "    if (isOpen) input.focus();",
      "  });",
      "",
      "  panel.querySelector('#gosumo-close').addEventListener('click', function() {",
      "    isOpen = false;",
      "    panel.style.display = 'none';",
      "  });",
      "",
      "  sendBtn.addEventListener('click', sendMessage);",
      "  input.addEventListener('keydown', function(e) {",
      "    if (e.key === 'Enter') sendMessage();",
      "  });",
      "})();",
    ].join("\n");

    res.send(js);
  }
}
