packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - msgpackr-extract
  - prisma
enablePrePostScripts: true
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
