import * as crypto from 'crypto';
import { ConfigurationError, generateId } from '@gosumo/shared';

/**
 * Signed session tokens for the WebChat widget.
 *
 * The WebChat gateway is the one channel where the *visitor* holds their own
 * session identifier. The widget keeps the id it was handed and replays it on
 * `chat:init` so a reconnect resumes the same thread rather than forking a new
 * one — which is the behaviour we want, but it means `chat:init` is an
 * unauthenticated resume keyed by a value the client supplies.
 *
 * Handed the raw id, the gateway cannot tell a session it minted from one
 * somebody typed. Supplying another visitor's id resolved to that visitor's
 * `channel_contacts` row, and so to their client and their conversation: the
 * attacker inherits the thread, and because `chat:init` also repoints the
 * outbound socket map, every subsequent agent or AI reply meant for the victim
 * is delivered to the attacker instead. The widget id that scopes the lookup is
 * no barrier — it sits in the page source of every site running the widget.
 *
 * So the id the visitor holds is an HMAC-SHA256 token over
 * `sessionId | widgetId | issuedAt`, verified on the way back in. Only the
 * signed form ever leaves the server; internally the gateway keys everything by
 * the raw `sessionId` inside it, so stored `channel_contacts.external_id`
 * values and emitted event payloads are unchanged.
 *
 * Binding the widget id into the payload matters as much as the signature: a
 * token is only valid for the widget it was minted for, so a token collected
 * from one tenant's site cannot resume a session against another's.
 *
 * Like {@link signOAuthState} this is deliberately stateless — no store to
 * provision or expire. A token is therefore replayable inside its TTL by
 * whoever holds it, which is the same trust level as the browser tab that
 * received it.
 */

/**
 * How long a visitor's session token stays resumable.
 *
 * Long enough to survive a reconnect, a flaky mobile handover, or stepping away
 * from the tab for a while; short enough that a token picked out of a log or a
 * shared browser stops working within a day.
 */
export const WEBCHAT_SESSION_TTL_MS = 24 * 60 * 60 * 1000;

interface WebChatSessionPayload {
  /** raw sessionId — what the gateway and the database key on */
  s: string;
  /** widgetId (channel_accounts.id) the session belongs to */
  w: string;
  /** issued-at, epoch ms */
  t: number;
}

/** A verified session token, unpacked. */
export interface WebChatSession {
  sessionId: string;
  widgetId: string;
}

function sign(payloadB64: string, secret: string): string {
  return crypto.createHmac('sha256', secret).update(payloadB64).digest('hex');
}

/**
 * Mint a signed session token for `widgetId`.
 *
 * @param sessionId Raw session id to wrap; a fresh one is generated by default.
 * @param issuedAt  Injectable clock for tests; defaults to now.
 */
export function signWebChatSession(
  widgetId: string,
  secret: string,
  sessionId: string = generateId(),
  issuedAt: number = Date.now(),
): string {
  if (!secret) {
    // An unsigned token is precisely the hole this module closes, so refuse to
    // mint one rather than quietly degrading to the forgeable version.
    throw new ConfigurationError(
      'JWT_SECRET',
      'Cannot sign a WebChat session without a secret',
    );
  }

  const payload: WebChatSessionPayload = { s: sessionId, w: widgetId, t: issuedAt };
  const payloadB64 = Buffer.from(JSON.stringify(payload)).toString('base64url');

  return `${payloadB64}.${sign(payloadB64, secret)}`;
}

/**
 * Recover the session a token names, or `null` when it is malformed, forged,
 * expired, or was minted for a different widget.
 *
 * Never throws — a bad token is an ordinary rejection. Callers treat `null` as
 * "start a fresh session", not as an error to surface to the visitor.
 *
 * @param expectedWidgetId When given, the token must have been minted for this
 *   widget. Omit only where the widget is not yet known.
 */
export function verifyWebChatSession(
  token: string,
  secret: string,
  expectedWidgetId?: string,
  ttlMs: number = WEBCHAT_SESSION_TTL_MS,
  now: number = Date.now(),
): WebChatSession | null {
  if (!token || !secret) return null;

  const separator = token.lastIndexOf('.');
  if (separator <= 0) return null;

  const payloadB64 = token.slice(0, separator);
  const signature = token.slice(separator + 1);
  const expected = sign(payloadB64, secret);

  // Constant-time, but only once the lengths match — timingSafeEqual throws on
  // a length mismatch, and the length of a hex digest is public anyway.
  const given = Buffer.from(signature);
  const want = Buffer.from(expected);
  if (given.length !== want.length) return null;
  if (!crypto.timingSafeEqual(given, want)) return null;

  let payload: WebChatSessionPayload;
  try {
    payload = JSON.parse(
      Buffer.from(payloadB64, 'base64url').toString('utf8'),
    ) as WebChatSessionPayload;
  } catch {
    return null;
  }

  if (typeof payload.s !== 'string' || !payload.s) return null;
  if (typeof payload.w !== 'string' || !payload.w) return null;
  if (typeof payload.t !== 'number' || !Number.isFinite(payload.t)) return null;

  // Reject stale tokens and ones stamped in the future alike — a future stamp
  // means either a tampered payload under a leaked secret, or clocks far enough
  // apart that the TTL means nothing.
  const age = now - payload.t;
  if (age < 0 || age > ttlMs) return null;

  // A signature proves we minted the token, not that it belongs here. Without
  // this check a token lifted from one tenant's site would resume a session
  // against another's widget.
  if (expectedWidgetId !== undefined && payload.w !== expectedWidgetId) return null;

  return { sessionId: payload.s, widgetId: payload.w };
}
