import { Inject, Injectable, Logger } from '@nestjs/common';
import * as crypto from 'crypto';
import { REDIS_CLIENT, RedisClient } from './redis.provider';
import { SessionDto } from './dto/session.dto';

/** Refresh-token / session lifetime — 7 days. */
export const SESSION_TTL_SECONDS = 7 * 24 * 60 * 60;
/** Maximum concurrent sessions per user; the oldest is evicted on overflow. */
export const MAX_CONCURRENT_SESSIONS = 5;

const sessionKey = (userId: string, sessionId: string): string =>
  `gosumo:session:${userId}:${sessionId}`;
/** Sorted-set index of a user's sessions, scored by creation time (ms). */
const sessionIndexKey = (userId: string): string => `gosumo:sessions:${userId}`;

export interface StoredSession {
  sessionId: string;
  userId: string;
  businessId: string;
  refreshTokenHash: string;
  ip: string | null;
  userAgent: string | null;
  createdAt: string;
  lastUsedAt: string;
}

export interface SessionMeta {
  ip?: string | null;
  userAgent?: string | null;
}

/**
 * Manages operator sessions in Redis. Each login creates a session that holds the
 * SHA-256 hash of its refresh token; access tokens carry the `sessionId` so a
 * revoked session immediately invalidates both token types.
 */
@Injectable()
export class SessionService {
  private readonly logger = new Logger(SessionService.name);

  constructor(@Inject(REDIS_CLIENT) private readonly redis: RedisClient) {}

  /**
   * Persist a new session for a user, enforcing the concurrent-session cap by
   * evicting the oldest session(s) first. The `sessionId` is generated by the
   * caller so it can be embedded in the access/refresh tokens before storage.
   */
  async createSession(
    userId: string,
    businessId: string,
    sessionId: string,
    refreshToken: string,
    meta: SessionMeta = {},
  ): Promise<void> {
    await this.evictOverflow(userId, MAX_CONCURRENT_SESSIONS - 1);

    const now = new Date().toISOString();
    const session: StoredSession = {
      sessionId,
      userId,
      businessId,
      refreshTokenHash: this.hashToken(refreshToken),
      ip: meta.ip ?? null,
      userAgent: meta.userAgent ?? null,
      createdAt: now,
      lastUsedAt: now,
    };

    await this.redis.set(
      sessionKey(userId, sessionId),
      JSON.stringify(session),
      'EX',
      SESSION_TTL_SECONDS,
    );
    await this.redis.zadd(sessionIndexKey(userId), Date.now(), sessionId);
    await this.redis.expire(sessionIndexKey(userId), SESSION_TTL_SECONDS);
  }

  /** True when the session still exists (i.e. has not expired or been revoked). */
  async isActive(userId: string, sessionId: string): Promise<boolean> {
    const exists = await this.redis.exists(sessionKey(userId, sessionId));
    return exists > 0;
  }

  async getSession(userId: string, sessionId: string): Promise<StoredSession | null> {
    const raw = await this.redis.get(sessionKey(userId, sessionId));
    if (!raw) {
      return null;
    }
    return JSON.parse(raw) as StoredSession;
  }

  /** Constant-time check that the supplied refresh token matches the stored hash. */
  async verifyRefreshToken(
    userId: string,
    sessionId: string,
    refreshToken: string,
  ): Promise<boolean> {
    const session = await this.getSession(userId, sessionId);
    if (!session) {
      return false;
    }
    const candidate = this.hashToken(refreshToken);
    const a = Buffer.from(candidate, 'hex');
    const b = Buffer.from(session.refreshTokenHash, 'hex');
    if (a.length !== b.length) {
      return false;
    }
    return crypto.timingSafeEqual(a, b);
  }

  /** Rotate the stored refresh-token hash (called on every token refresh). */
  async rotateRefreshToken(
    userId: string,
    sessionId: string,
    newRefreshToken: string,
  ): Promise<void> {
    const session = await this.getSession(userId, sessionId);
    if (!session) {
      return;
    }
    session.refreshTokenHash = this.hashToken(newRefreshToken);
    session.lastUsedAt = new Date().toISOString();
    await this.redis.set(
      sessionKey(userId, sessionId),
      JSON.stringify(session),
      'EX',
      SESSION_TTL_SECONDS,
    );
    await this.redis.expire(sessionIndexKey(userId), SESSION_TTL_SECONDS);
  }

  /** Update the `lastUsedAt` marker; best-effort, never throws into the request path. */
  async touch(userId: string, sessionId: string): Promise<void> {
    const session = await this.getSession(userId, sessionId);
    if (!session) {
      return;
    }
    session.lastUsedAt = new Date().toISOString();
    await this.redis.set(
      sessionKey(userId, sessionId),
      JSON.stringify(session),
      'EX',
      SESSION_TTL_SECONDS,
    );
  }

  async listSessions(userId: string, currentSessionId?: string): Promise<SessionDto[]> {
    const ids = await this.redis.zrange(sessionIndexKey(userId), 0, -1);
    if (ids.length === 0) {
      return [];
    }
    const raws = await this.redis.mget(...ids.map((id) => sessionKey(userId, id)));

    const sessions: SessionDto[] = [];
    for (let i = 0; i < ids.length; i++) {
      const raw = raws[i];
      const id = ids[i]!;
      if (!raw) {
        // Stale index entry (session TTL'd out) — clean it up lazily.
        await this.redis.zrem(sessionIndexKey(userId), id);
        continue;
      }
      const s = JSON.parse(raw) as StoredSession;
      sessions.push({
        sessionId: s.sessionId,
        ip: s.ip,
        userAgent: s.userAgent,
        createdAt: s.createdAt,
        lastUsedAt: s.lastUsedAt,
        isCurrent: currentSessionId === s.sessionId,
      });
    }
    return sessions;
  }

  async revokeSession(userId: string, sessionId: string): Promise<void> {
    await this.redis.del(sessionKey(userId, sessionId));
    await this.redis.zrem(sessionIndexKey(userId), sessionId);
  }

  async revokeAllSessions(userId: string): Promise<void> {
    const ids = await this.redis.zrange(sessionIndexKey(userId), 0, -1);
    if (ids.length > 0) {
      await this.redis.del(...ids.map((id) => sessionKey(userId, id)));
    }
    await this.redis.del(sessionIndexKey(userId));
  }

  /**
   * Trim a user's sessions down to at most `keep`, removing the oldest first.
   * Used before inserting a new session so the live count never exceeds the cap.
   */
  private async evictOverflow(userId: string, keep: number): Promise<void> {
    const count = await this.redis.zcard(sessionIndexKey(userId));
    const excess = count - keep;
    if (excess <= 0) {
      return;
    }
    const oldest = await this.redis.zrange(sessionIndexKey(userId), 0, excess - 1);
    for (const id of oldest) {
      await this.redis.del(sessionKey(userId, id));
      await this.redis.zrem(sessionIndexKey(userId), id);
    }
    this.logger.debug(`Evicted ${oldest.length} oldest session(s) for user ${userId}`);
  }

  private hashToken(token: string): string {
    return crypto.createHash('sha256').update(token).digest('hex');
  }
}
