import {
  IsString,
  IsUUID,
  IsEnum,
  IsOptional,
  IsObject,
  IsBoolean,
  IsNumber,
  IsInt,
  IsNotEmpty,
  IsDateString,
  Min,
  Max,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { ChannelType, MessageStatus, MessageDirection } from '@gosumo/shared';

// ─────────────────────────────────────────────
// StoreInboundMessageDto
// ─────────────────────────────────────────────

export class StoreInboundMessageDto {
  @ApiProperty({ description: 'Conversation UUID' })
  @IsUUID()
  conversationId!: string;

  @ApiProperty({ description: 'Channel account UUID' })
  @IsUUID()
  channelAccountId!: string;

  @ApiProperty({ enum: ChannelType, description: 'Channel type' })
  @IsEnum(ChannelType)
  channel!: ChannelType;

  @ApiProperty({ description: 'Channel-assigned external message ID' })
  @IsString()
  externalId!: string;

  @ApiProperty({ description: 'Sender type: CLIENT or SYSTEM' })
  @IsString()
  senderType!: string;

  @ApiPropertyOptional({ description: 'Sender UUID (client_id or system actor)' })
  @IsOptional()
  @IsUUID()
  senderId?: string;

  @ApiProperty({ description: 'Message content payload (JSON)' })
  @IsObject()
  content!: Record<string, unknown>;

  @ApiPropertyOptional({ description: 'Extracted text content for search' })
  @IsOptional()
  @IsString()
  textContent?: string;

  @ApiPropertyOptional({ description: 'Additional metadata' })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;
}

// ─────────────────────────────────────────────
// StoreOutboundMessageDto
// ─────────────────────────────────────────────

export class StoreOutboundMessageDto {
  @ApiProperty({ description: 'Conversation UUID' })
  @IsUUID()
  conversationId!: string;

  @ApiProperty({ description: 'Channel account UUID' })
  @IsUUID()
  channelAccountId!: string;

  @ApiProperty({ enum: ChannelType, description: 'Channel type' })
  @IsEnum(ChannelType)
  channel!: ChannelType;

  @ApiProperty({ description: 'Sender type: AI, HUMAN_AGENT, or SYSTEM' })
  @IsString()
  senderType!: string;

  @ApiPropertyOptional({ description: 'Sender UUID (team_member_id or system actor)' })
  @IsOptional()
  @IsUUID()
  senderId?: string;

  @ApiProperty({ description: 'Message content payload (JSON)' })
  @IsObject()
  content!: Record<string, unknown>;

  @ApiPropertyOptional({ description: 'Extracted text content for search' })
  @IsOptional()
  @IsString()
  textContent?: string;

  @ApiPropertyOptional({ description: 'Channel-assigned external message ID' })
  @IsOptional()
  @IsString()
  externalId?: string;

  @ApiPropertyOptional({ description: 'Whether this message was generated by AI' })
  @IsOptional()
  @IsBoolean()
  isAiGenerated?: boolean;

  @ApiPropertyOptional({ description: 'AI confidence score (0.0000 to 1.0000)' })
  @IsOptional()
  @IsNumber()
  confidenceScore?: number;

  @ApiPropertyOptional({ description: 'AI decision UUID that produced this message' })
  @IsOptional()
  @IsUUID()
  aiDecisionId?: string;

  @ApiPropertyOptional({ description: 'Additional metadata' })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;
}

// ─────────────────────────────────────────────
// MessagePaginationQueryDto
// ─────────────────────────────────────────────

export class MessagePaginationQueryDto {
  @ApiPropertyOptional({
    description: 'Number of messages to return (1-100)',
    default: 20,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(100)
  @Type(() => Number)
  limit?: number = 20;

  @ApiPropertyOptional({
    description: 'Base64-encoded cursor for pagination',
  })
  @IsOptional()
  @IsString()
  cursor?: string;
}

// ─────────────────────────────────────────────
// MessageSearchQueryDto
// ─────────────────────────────────────────────

export class MessageSearchQueryDto {
  @ApiProperty({ description: 'Search query string' })
  @IsString()
  @IsNotEmpty()
  q!: string;

  @ApiPropertyOptional({ description: 'Filter by conversation UUID' })
  @IsOptional()
  @IsUUID()
  conversationId?: string;

  @ApiPropertyOptional({ description: 'Filter by start date (ISO-8601)' })
  @IsOptional()
  @IsDateString()
  dateFrom?: string;

  @ApiPropertyOptional({ description: 'Filter by end date (ISO-8601)' })
  @IsOptional()
  @IsDateString()
  dateTo?: string;
}

// ─────────────────────────────────────────────
// UpdateDeliveryStatusDto
// ─────────────────────────────────────────────

export class UpdateDeliveryStatusDto {
  @ApiProperty({ enum: MessageStatus, description: 'New delivery status' })
  @IsEnum(MessageStatus)
  status!: MessageStatus;

  @ApiPropertyOptional({ description: 'Timestamp when message was delivered' })
  @IsOptional()
  @IsDateString()
  deliveredAt?: string;

  @ApiPropertyOptional({ description: 'Timestamp when message was read' })
  @IsOptional()
  @IsDateString()
  readAt?: string;

  @ApiPropertyOptional({ description: 'Timestamp when message delivery failed' })
  @IsOptional()
  @IsDateString()
  failedAt?: string;

  @ApiPropertyOptional({ description: 'Reason for delivery failure' })
  @IsOptional()
  @IsString()
  failureReason?: string;
}

// ─────────────────────────────────────────────
// AttachAIMetadataDto
// ─────────────────────────────────────────────

export class AttachAIMetadataDto {
  @ApiProperty({ description: 'Whether this message was generated by AI' })
  @IsBoolean()
  isAiGenerated!: boolean;

  @ApiPropertyOptional({ description: 'AI confidence score (0.0000 to 1.0000)' })
  @IsOptional()
  @IsNumber()
  confidenceScore?: number;

  @ApiPropertyOptional({ description: 'AI decision UUID' })
  @IsOptional()
  @IsUUID()
  aiDecisionId?: string;
}

// ─────────────────────────────────────────────
// MessageResponseDto
// ─────────────────────────────────────────────

export class MessageResponseDto {
  @ApiProperty() id!: string;
  @ApiProperty() businessId!: string;
  @ApiProperty() conversationId!: string;
  @ApiProperty() channelAccountId!: string;
  @ApiProperty({ enum: MessageDirection }) direction!: string;
  @ApiProperty() type!: string;
  @ApiProperty({ enum: MessageStatus }) status!: string;
  @ApiProperty() senderType!: string;
  @ApiPropertyOptional() senderId?: string | null;
  @ApiProperty() content!: Record<string, unknown>;
  @ApiPropertyOptional() externalId?: string | null;
  @ApiPropertyOptional() externalStatus?: string | null;
  @ApiPropertyOptional() deliveredAt?: string | null;
  @ApiPropertyOptional() readAt?: string | null;
  @ApiPropertyOptional() failedAt?: string | null;
  @ApiPropertyOptional() failureReason?: string | null;
  @ApiPropertyOptional() aiDecisionId?: string | null;
  @ApiProperty() isAiGenerated!: boolean;
  @ApiPropertyOptional() confidenceScore?: string | null;
  @ApiPropertyOptional() campaignId?: string | null;
  @ApiProperty() reactions!: unknown[];
  @ApiPropertyOptional() textContent?: string | null;
  @ApiProperty() metadata!: Record<string, unknown>;
  @ApiPropertyOptional() sentAt?: string | null;
  @ApiProperty() createdAt!: string;
  @ApiProperty() updatedAt!: string;
}
