import {
  IsString,
  IsUUID,
  IsEnum,
  IsOptional,
  IsObject,
  IsBoolean,
  IsNumber,
  IsInt,
  IsNotEmpty,
  IsDateString,
  IsArray,
  MaxLength,
  Min,
  Max,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { ChannelType, MessageStatus, MessageDirection } from '@gosumo/shared';
import { NotificationTemplateChannel } from '@prisma/client';

// ─────────────────────────────────────────────
// StoreInboundMessageDto
// ─────────────────────────────────────────────

export class StoreInboundMessageDto {
  @ApiProperty({ description: 'Conversation UUID' })
  @IsUUID()
  conversationId!: string;

  @ApiProperty({ description: 'Channel account UUID' })
  @IsUUID()
  channelAccountId!: string;

  @ApiProperty({ enum: ChannelType, description: 'Channel type' })
  @IsEnum(ChannelType)
  channel!: ChannelType;

  @ApiProperty({ description: 'Channel-assigned external message ID' })
  @IsString()
  externalId!: string;

  @ApiProperty({ description: 'Sender type: CLIENT or SYSTEM' })
  @IsString()
  senderType!: string;

  @ApiPropertyOptional({ description: 'Sender UUID (client_id or system actor)' })
  @IsOptional()
  @IsUUID()
  senderId?: string;

  @ApiProperty({ description: 'Message content payload (JSON)' })
  @IsObject()
  content!: Record<string, unknown>;

  @ApiPropertyOptional({ description: 'Extracted text content for search' })
  @IsOptional()
  @IsString()
  textContent?: string;

  @ApiPropertyOptional({ description: 'Message this one replies to (threading)' })
  @IsOptional()
  @IsUUID()
  replyToMessageId?: string;

  @ApiPropertyOptional({ description: 'Additional metadata' })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;
}

// ─────────────────────────────────────────────
// StoreOutboundMessageDto
// ─────────────────────────────────────────────

export class StoreOutboundMessageDto {
  @ApiProperty({ description: 'Conversation UUID' })
  @IsUUID()
  conversationId!: string;

  @ApiProperty({ description: 'Channel account UUID' })
  @IsUUID()
  channelAccountId!: string;

  @ApiProperty({ enum: ChannelType, description: 'Channel type' })
  @IsEnum(ChannelType)
  channel!: ChannelType;

  @ApiProperty({ description: 'Sender type: AI, HUMAN_AGENT, or SYSTEM' })
  @IsString()
  senderType!: string;

  @ApiPropertyOptional({ description: 'Sender UUID (team_member_id or system actor)' })
  @IsOptional()
  @IsUUID()
  senderId?: string;

  @ApiProperty({ description: 'Message content payload (JSON)' })
  @IsObject()
  content!: Record<string, unknown>;

  @ApiPropertyOptional({ description: 'Extracted text content for search' })
  @IsOptional()
  @IsString()
  textContent?: string;

  @ApiPropertyOptional({ description: 'Channel-assigned external message ID' })
  @IsOptional()
  @IsString()
  externalId?: string;

  @ApiPropertyOptional({ description: 'Whether this message was generated by AI' })
  @IsOptional()
  @IsBoolean()
  isAiGenerated?: boolean;

  @ApiPropertyOptional({ description: 'AI confidence score (0.0000 to 1.0000)' })
  @IsOptional()
  @IsNumber()
  confidenceScore?: number;

  @ApiPropertyOptional({ description: 'AI decision UUID that produced this message' })
  @IsOptional()
  @IsUUID()
  aiDecisionId?: string;

  @ApiPropertyOptional({ description: 'Message this one replies to (threading)' })
  @IsOptional()
  @IsUUID()
  replyToMessageId?: string;

  @ApiPropertyOptional({ description: 'Additional metadata' })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;
}

// ─────────────────────────────────────────────
// MessagePaginationQueryDto
// ─────────────────────────────────────────────

export class MessagePaginationQueryDto {
  @ApiPropertyOptional({
    description: 'Number of messages to return (1-100)',
    default: 20,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(100)
  @Type(() => Number)
  limit?: number = 20;

  @ApiPropertyOptional({
    description: 'Base64-encoded cursor for pagination',
  })
  @IsOptional()
  @IsString()
  cursor?: string;
}

// ─────────────────────────────────────────────
// MessageSearchQueryDto
// ─────────────────────────────────────────────

export class MessageSearchQueryDto {
  @ApiProperty({ description: 'Search query string' })
  @IsString()
  @IsNotEmpty()
  q!: string;

  @ApiPropertyOptional({ description: 'Filter by conversation UUID' })
  @IsOptional()
  @IsUUID()
  conversationId?: string;

  @ApiPropertyOptional({ description: 'Filter by start date (ISO-8601)' })
  @IsOptional()
  @IsDateString()
  dateFrom?: string;

  @ApiPropertyOptional({ description: 'Filter by end date (ISO-8601)' })
  @IsOptional()
  @IsDateString()
  dateTo?: string;
}

// ─────────────────────────────────────────────
// UpdateDeliveryStatusDto
// ─────────────────────────────────────────────

export class UpdateDeliveryStatusDto {
  @ApiProperty({ enum: MessageStatus, description: 'New delivery status' })
  @IsEnum(MessageStatus)
  status!: MessageStatus;

  @ApiPropertyOptional({ description: 'Timestamp when message was delivered' })
  @IsOptional()
  @IsDateString()
  deliveredAt?: string;

  @ApiPropertyOptional({ description: 'Timestamp when message was read' })
  @IsOptional()
  @IsDateString()
  readAt?: string;

  @ApiPropertyOptional({ description: 'Timestamp when message delivery failed' })
  @IsOptional()
  @IsDateString()
  failedAt?: string;

  @ApiPropertyOptional({ description: 'Reason for delivery failure' })
  @IsOptional()
  @IsString()
  failureReason?: string;
}

// ─────────────────────────────────────────────
// AttachAIMetadataDto
// ─────────────────────────────────────────────

export class AttachAIMetadataDto {
  @ApiProperty({ description: 'Whether this message was generated by AI' })
  @IsBoolean()
  isAiGenerated!: boolean;

  @ApiPropertyOptional({ description: 'AI confidence score (0.0000 to 1.0000)' })
  @IsOptional()
  @IsNumber()
  confidenceScore?: number;

  @ApiPropertyOptional({ description: 'AI decision UUID' })
  @IsOptional()
  @IsUUID()
  aiDecisionId?: string;
}

// ─────────────────────────────────────────────
// MessageResponseDto
// ─────────────────────────────────────────────

export class MessageResponseDto {
  @ApiProperty() id!: string;
  @ApiProperty() businessId!: string;
  @ApiProperty() conversationId!: string;
  @ApiProperty() channelAccountId!: string;
  @ApiProperty({ enum: MessageDirection }) direction!: string;
  @ApiProperty() type!: string;
  @ApiProperty({ enum: MessageStatus }) status!: string;
  @ApiProperty() senderType!: string;
  @ApiPropertyOptional() senderId?: string | null;
  @ApiProperty() content!: Record<string, unknown>;
  @ApiPropertyOptional() externalId?: string | null;
  @ApiPropertyOptional() externalStatus?: string | null;
  @ApiPropertyOptional() deliveredAt?: string | null;
  @ApiPropertyOptional() readAt?: string | null;
  @ApiPropertyOptional() failedAt?: string | null;
  @ApiPropertyOptional() failureReason?: string | null;
  @ApiPropertyOptional() aiDecisionId?: string | null;
  @ApiProperty() isAiGenerated!: boolean;
  @ApiPropertyOptional() confidenceScore?: string | null;
  @ApiPropertyOptional() campaignId?: string | null;
  @ApiProperty() reactions!: unknown[];
  @ApiPropertyOptional() textContent?: string | null;
  @ApiProperty() metadata!: Record<string, unknown>;
  @ApiPropertyOptional() sentAt?: string | null;
  @ApiProperty() createdAt!: string;
  @ApiProperty() updatedAt!: string;
}

// ─────────────────────────────────────────────
// AttachMediaDto
// ─────────────────────────────────────────────

export class AttachMediaDto {
  @ApiProperty({ description: 'Content type: IMAGE | VIDEO | AUDIO | DOCUMENT' })
  @IsString()
  type!: string;

  @ApiProperty({ description: 'Original filename' })
  @IsString()
  @MaxLength(500)
  filename!: string;

  @ApiProperty({ description: 'MIME type' })
  @IsString()
  mimeType!: string;

  @ApiProperty({ description: 'File size in bytes' })
  @Type(() => Number)
  @IsInt()
  @Min(0)
  sizeBytes!: number;

  @ApiProperty({ description: 'GoSumo S3 object key (never a channel CDN URL)' })
  @IsString()
  storageKey!: string;

  @ApiPropertyOptional({ description: 'Public CDN URL after processing' })
  @IsOptional()
  @IsString()
  cdnUrl?: string;

  @ApiPropertyOptional({ description: 'Image/video width in px' })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  width?: number;

  @ApiPropertyOptional({ description: 'Image/video height in px' })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  height?: number;

  @ApiPropertyOptional({ description: 'Whether the file is publicly accessible' })
  @IsOptional()
  @IsBoolean()
  isPublic?: boolean;
}

// ─────────────────────────────────────────────
// ReactionDto
// ─────────────────────────────────────────────

export class ReactionDto {
  @ApiProperty({ description: 'Reaction emoji' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(16)
  emoji!: string;

  @ApiProperty({ description: 'UUID of the reacting sender (client or member)' })
  @IsUUID()
  senderId!: string;
}

// ─────────────────────────────────────────────
// Template / quick-reply DTOs
// ─────────────────────────────────────────────

export class CreateTemplateDto {
  @ApiProperty({ enum: NotificationTemplateChannel, description: 'Template channel' })
  @IsEnum(NotificationTemplateChannel)
  channel!: NotificationTemplateChannel;

  @ApiProperty({ description: 'Template name (unique per business + channel)' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  name!: string;

  @ApiProperty({ description: 'Channel structure; must include a `body` string' })
  @IsObject()
  content!: Record<string, unknown>;

  @ApiPropertyOptional({ description: 'Declared variable names', type: [String] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  variables?: string[];

  @ApiPropertyOptional({ description: 'Category, e.g. MARKETING | UTILITY | QUICK_REPLY' })
  @IsOptional()
  @IsString()
  category?: string;

  @ApiPropertyOptional({ description: 'Language code', default: 'en' })
  @IsOptional()
  @IsString()
  language?: string;

  @ApiPropertyOptional({ description: 'Channel-approved external template name' })
  @IsOptional()
  @IsString()
  externalName?: string;
}

export class CreateQuickReplyDto {
  @ApiProperty({ description: 'Quick-reply name' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  name!: string;

  @ApiProperty({ description: 'Body text (supports {{placeholders}})' })
  @IsString()
  @IsNotEmpty()
  body!: string;

  @ApiPropertyOptional({ enum: NotificationTemplateChannel, description: 'Channel' })
  @IsOptional()
  @IsEnum(NotificationTemplateChannel)
  channel?: NotificationTemplateChannel;
}

export class RenderTemplateDto {
  @ApiPropertyOptional({ description: 'Variable values to substitute' })
  @IsOptional()
  @IsObject()
  variables?: Record<string, string>;
}

export class ListTemplatesQueryDto {
  @ApiPropertyOptional({ enum: NotificationTemplateChannel, description: 'Filter by channel' })
  @IsOptional()
  @IsEnum(NotificationTemplateChannel)
  channel?: NotificationTemplateChannel;

  @ApiPropertyOptional({ description: 'Filter by category' })
  @IsOptional()
  @IsString()
  category?: string;
}
